### PR TITLE
Joss updates

### LINKED ISSUE #61: Expanding introduction at beginning of README
Submitting as part of JOSS review openjournals/joss-reviews#3397

While the introduction notebooks do give a good summary of what problems the software is designed to solve and who the target audience is, the introduction at the beginning of the README file is currently a bit lacking in detail. I would suggest adding a couple of sentences defining what ecological inference is  and what functionality PyEI offers.

### LINKED ISSUE #64: `lint_and_test.sh` script not running tests
Submitting as part of JOSS review openjournals/joss-reviews#3397

The script `scripts/lint_and_test.sh` currently does not run the tests on my machine (running code as of  2d47262e413a4e17db1eead0924cff164e57f01b on Ubuntu 20.04). It seems that the `pylint` check may be returning an error status which due to the `set -ex` call then causes the script to exit without running the `scripts/test.sh` script. Running `scripts/test.sh` directly works however.

### LINKED ISSUE #65: No mention of possibility of installing directly from PyPI
Submitting as part of JOSS review openjournals/joss-reviews#3397

While the package has releases on `PyPi` the installation instructions suggest to install directly from GitHub rather than running `pip install pyei`. Is this intentional? If you want the default to be installing from the latest version on the `main` branch it may still be worth adding a pointer to the PyPI version as an alternative less up-to-date but potentially more stable version.

### LINKED ISSUE #66: Enhancing `conda` environment set up instructions
Submitting as part of JOSS review openjournals/joss-reviews#3397

In the 'Install with conda' instructions in the README file the `conda install pip` line is (I think) unnecessary as I think installing `python` in a `conda` environment will also always install `pip`. All of the requirements also seem to available as `conda` packages if the `conda-forge` channel is used, so to [avoid mixing `conda` and `pip`](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) an alternative to create the environment and install all of the dependencies would be
```
conda create --name pyei --channel conda-forge python=3.8 --file requirements.txt --file requirements-dev.txt
```

### LINKED ISSUE #68: Use of i.i.d. in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

https://github.com/mggg/ecological-inference/blob/2d47262e413a4e17db1eead0924cff164e57f01b/paper/paper.md#L68

'i.i.d.' should be defined on first usage, also independent may be better as 'i.i.d. samples from the posterior distribution' is somewhat redundant as 'from the posterior distribution' already implies the samples are identically distributed.

### LINKED ISSUE #70: Clarification of assumptions required for dimension scaling results in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

https://github.com/mggg/ecological-inference/blob/2d47262e413a4e17db1eead0924cff164e57f01b/paper/paper.md#L68

The claim regarding the scaling with dimension for Metropolis&ndash;Hastings versus Hamiltonian Monte Carlo (in the sentence in lines 65&ndash;69 in proof PDF) should ideally have a clarification that the result requires assumptions on the target distribution (in particular that it is a product of independent factors in each dimension) to hold. To avoid having to introduce technical details this could just simply be adding 'Under certain assumptions on the target posterior distribution,' at the beginning of the sentence.

### LINKED ISSUE #71: Incorrect capitlization in references in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

Some capitalization in the references in `paper/paper.bib` needs fixing by adding braces `{}`, for example, 'bayesian' &rightarrow; 'Bayesian', 'python' &rightarrow; 'Python', 'goodman' &rightarrow; 'Goodman', 'hamiltonian' &rightarrow; 'Hamiltonian, 'monte' &rightarrow; 'Monte', 'carlo' &rightarrow; 'Carlo'.

### LINKED ISSUE #72: Reducing number of example plots in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

While it is nice to have a couple of example outputs, I feel that five is possibly excessive. The example notebooks already provide a venue for giving a more exhaustive tour of the plotting functionality while I would say the aim in the paper is just to support the assertions in paragraph in lines 75--76 in the proof PDF. To me selecting one or two key plots and including in the text rather than at the end would be preferable.

### LINKED ISSUE #73: KDE not defined in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

https://github.com/mggg/ecological-inference/blob/2d47262e413a4e17db1eead0924cff164e57f01b/paper/paper.md#L83

The acronym KDE in the caption should be defined.

### LINKED ISSUE #74: Adding further reference for MCMC algorithm used in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

https://github.com/mggg/ecological-inference/blob/2d47262e413a4e17db1eead0924cff164e57f01b/paper/paper.md#L68

The default sampler in PyMC3, as with Stan, I believe uses an updated algorithm that includes several improvements over the original NUTS algorithm. [Betancourt (2017)](https://arxiv.org/abs/1701.02434) describes the main improvements and so would be a worthwhile additional reference in line 60 in the proof PDF.

### LINKED ISSUE #75: Removing parentheses around paragraph in paper
Submitting as part of JOSS review openjournals/joss-reviews#3397

https://github.com/mggg/ecological-inference/blob/2d47262e413a4e17db1eead0924cff164e57f01b/paper/paper.md#L61

The parentheses around this paragraph (lines 45&ndash;47 in the proof PDF) is, I think, unnecessary and interrupts the flow of the paper.

### LINKED ISSUE #76: Nested parens in citation
Submitting as part of JOSS review openjournals/joss-reviews#3397

In the paper, one of the references comes out as `(see especially (King, 1997))` with nested parentheses. As the JOSS format is (I think) RMarkdown, you can avoid this by putting the parenthetical text in the citation square brackets: `[see especially @king1997solution]` or whatever.

### PR DESCRIPTION
**Pull request by karink520**
A bunch of small updates to paper.md and README.md

fixes #76
fixes #75 
fixes #74
fixes #73
fixes #72
fixes #71 
fixes #70
fixes #68
fixes #66
fixes #65
fixes #64
fixes #61

### CODE REVIEW

**Review by gabeschoenbach — COMMENTED** [review]
This all looks good! My only thoughts/suggestions have to do with the installation instructions in the README:
- I tried running `pip install pyei` on my base conda environment and got an error (traceback at the bottom of this review). I tried running `pip uninstall pyei` and then reinstalling, and it worked fine...
- I like the cleaner one-line conda install to get the development environment up and running. But after we do that and activate the environment, we should run `pip install pyei` to get `pyei` in that environment as well, no? Can we just add it to the `requirements.txt`?

Below is the error from running `pip install pyei`. I think it was just happening because I had already had an older version of `pyei` installed, but wanted to document the error here just in case you're interested...
```
ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 520, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_internal/operations/check.py", line 50, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/Users/gabe/miniconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gabe/miniconda3/lib/python3.8/site-packages/maup-0.7.dist-info/METADATA'
```

**Comment by karink520** [comment]
Thanks!
Re: point 1. Right, I'm not concerned either, but thanks for documenting it here, in case this issue comes up for someone else.

Re: point 2. Thanks for bringing this up. I'm going to add back in the in `pip install -e .`, which will install pyei into the current environment (when run from the directory where someone has cloned pyei. Without it, at least in my setup, I can't run the notebooks right away, and we need it to make pytest work too.

**Comment by karink520** [comment]
Also fixes #62, fixes #67, fixes #69

Added `pip install -e .` back into dev installation instructions

**Comment by karink520** [comment]
Also fixes #63, fixes #77

**Review by gabeschoenbach — APPROVED** [review]
Looks good!

**Pull request merged**
