### PR TITLE
add descriptive text to readme to provide more context about racially…

### PR DESCRIPTION
**Pull request by tahentx**
… polarized voting

### CODE REVIEW

**Comment by karink520** [comment]
This looks like helpful context to me! What do you think of adding something similar/the same to the "introduction to EI" notebook pyei/intro_notebooks/Introduction_to_EI.ipynb? It strikes me as helpful enough that I think it might be good to have in both places.

**Comment by tahentx** [comment]
Great idea! I'll add some similar comments in both.

**Comment by tahentx** [comment]
@karink520 I have a suggestion for what I think could be better: perhaps I can put together a notebook oriented around the legal concepts "EI for RPV", and then we can link to it in the intro notebooks. The narrative in the intro notebooks has a nice flow, and I don't want to force anything in. Thoughts?

**Comment by karink520** [comment]
That makes sense to me. I'll merge this PR for now, then, with the readme updates!

**Pull request merged**
